name: first-web-app build and deploy to remote wildfly

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with maven
        id: mvn_build_1
        run: |
          cd firstapp
          mvn --batch-mode --update-snapshots wildfly:undeploy wildfly:deploy \
          -Dwildfly.hostname=${{ secrets.WILDFLY_HOST }} \
          -Dwildfly.username=${{ secrets.WILDFLY_ADMIN_LOGIN }} \
          -Dwildfly.password=${{ secrets.WILDFLY_ADMIN_PASSWORD }}

      - name: Build with maven
          id: mvn_build_2
          run: |
            cd first-jsp-app
            mvn --batch-mode --update-snapshots wildfly:undeploy wildfly:deploy \
            -Dwildfly.hostname=${{ secrets.WILDFLY_HOST }} \
            -Dwildfly.username=${{ secrets.WILDFLY_ADMIN_LOGIN }} \
            -Dwildfly.password=${{ secrets.WILDFLY_ADMIN_PASSWORD }}